language: ruby 
rvm:
  - 2.5.3
services:
  - postgresql
before_script:
  - psql -c 'create database chestmasters_test;' -U postgres
before_install:
  - gem update --system
  - gem install bundler
script: 
  - bundle exec rake db:setup
  - bundle exec rake spec
